import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type LangCode = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr';

export const LANGUAGES: { code: LangCode; label: string; native: string; flag: string }[] = [
  { code: 'en', label: 'English',   native: 'English',    flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi',     native: 'हिन्दी',      flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali',   native: 'বাংলা',       flag: '🇧🇩' },
  { code: 'ta', label: 'Tamil',     native: 'தமிழ்',       flag: '🇮🇳' },
  { code: 'te', label: 'Telugu',    native: 'తెలుగు',      flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi',   native: 'मराठी',       flag: '🇮🇳' },
];

type Translations = Record<string, string>;

const T: Record<LangCode, Translations> = {
  en: {
    /* nav */
    nav_sessions: 'Sessions', nav_notes: 'Notes', nav_materials: 'Materials',
    nav_progress: 'Progress', nav_checkin: 'Check-in', nav_achievements: 'Achievements',
    nav_quiz: 'Quiz', nav_simulate: 'Simulate', nav_mentor: 'Mentor', nav_twin: 'Twin',
    /* common */
    sign_out: 'Sign out', loading: 'Loading…', live: 'Live',
    save: 'Save', cancel: 'Cancel', delete: 'Delete', close: 'Close',
    back_dashboard: '← Dashboard',
    /* greeting */
    greeting_midnight: 'Burning midnight oil', greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon', greeting_evening: 'Good evening',
    hero_sub: 'Ready to make today count?',
    /* dashboard stats */
    stat_sessions: 'Sessions', stat_hours: 'Hours Studied', stat_streak: 'Day Streak',
    stat_notes: 'Notes', stat_badges: 'Badges Earned',
    /* dashboard chart */
    chart_title: 'Study Hours — Last 7 Days', chart_log_today: '+ Log today',
    chart_this_week: 'This week', chart_daily_avg: 'Daily avg',
    no_data_title: 'No study data yet', no_data_sub: 'Log your first check-in to see your chart.',
    no_data_btn: 'Log today →',
    /* quick actions */
    quick_actions: 'Quick Actions',
    qa_sessions: 'Sessions', qa_materials: 'Materials', qa_progress: 'Progress',
    qa_quiz: 'Quiz', qa_predict: 'Predict', qa_achievements: 'Achievements',
    qa_simulate: 'Simulate', qa_mentor: 'Mentor', qa_twin: 'Twin',
    qa_checkin: 'Check-in', qa_language: 'Language',
    qa_desc_study: 'Study', qa_desc_upload: 'Upload', qa_desc_analytics: 'Analytics',
    qa_desc_quiz: 'AI Quiz', qa_desc_ml: 'ML Score', qa_desc_badges: 'Badges',
    qa_desc_whatif: 'What-If', qa_desc_advice: 'AI Advice', qa_desc_twin: 'Digital Twin',
    qa_desc_log: 'Log Today', qa_desc_language: 'Switch',
    /* study plan */
    my_study_plan: 'My Study Plan', generate_new: 'Generate new →', view_full_plan: 'View Full Plan',
    no_plan_title: 'No saved study plan yet',
    no_plan_sub: 'Generate a personalized 30-day plan in the AI Mentor.',
    go_to_mentor: 'Go to Mentor →', plan_saved: 'Saved',
    modal_plan_title: '30-Day Study Plan', modal_regenerate: 'Regenerate in Mentor →',
    /* language modal */
    language_title: 'Choose Language', language_select: 'Select your preferred language',
    /* login */
    login_tagline: 'Your AI-powered academic twin', login_title: 'Welcome back',
    login_email: 'Email', login_password: 'Password', login_forgot: 'Forgot Password?',
    login_btn: 'Sign in →', login_btn_loading: 'Signing in…',
    login_no_account: 'No account?', login_create: 'Create one',
    login_error: 'Invalid email or password.',
    /* register */
    register_title: 'Create your account', register_fullname: 'Full name',
    register_email: 'Email', register_password: 'Password',
    register_btn: 'Get started →', register_btn_loading: 'Creating account…',
    register_have_account: 'Already have an account?', register_signin: 'Sign in',
    register_error: 'Registration failed. Please try again.',
    /* forgot / reset */
    forgot_title: 'Forgot Password', forgot_email: 'Email address',
    forgot_btn: 'Send reset link', forgot_btn_loading: 'Sending…',
    forgot_back: 'Back to sign in', forgot_success: 'Reset link sent! Check your inbox.',
    reset_title: 'Reset Password', reset_new_pw: 'New Password', reset_confirm_pw: 'Confirm Password',
    reset_btn: 'Reset Password', reset_btn_loading: 'Resetting…', reset_mismatch: 'Passwords do not match.',
    /* profile */
    profile_title: 'Profile', profile_name: 'Full Name', profile_save_name: 'Save Name',
    profile_saving: 'Saving…', profile_change_pw: 'Change Password',
    profile_current_pw: 'Current Password', profile_new_pw: 'New Password',
    profile_save_pw: 'Update Password', profile_avatar: 'Profile Picture',
    profile_change_avatar: 'Change Photo', profile_uploading: 'Uploading…',
    /* sessions */
    sessions_title: 'Study Sessions', sessions_new: '+ New Session',
    sessions_create_title: 'New Study Session', sessions_form_title: 'Session title',
    sessions_form_subject: 'Subject', sessions_form_subject_ph: 'Select subject…',
    sessions_form_create: 'Create Session', sessions_form_creating: 'Creating…',
    sessions_form_cancel: 'Cancel', sessions_active: 'Active',
    sessions_completed: 'Completed', sessions_mark_done: 'Mark done',
    sessions_mark_active: 'Mark active', sessions_delete: 'Delete',
    sessions_empty: 'No sessions yet', sessions_empty_sub: 'Create your first study session above.',
    /* notes */
    notes_title: 'Notes', notes_new: '+ New note', notes_untitled: 'Untitled note',
    notes_placeholder: 'Start writing…', notes_save: 'Save',
    notes_saving: 'Saving…', notes_saved: 'Saved ✓', notes_delete: 'Delete',
    notes_empty: 'No notes yet', notes_empty_sub: 'Create a note to get started.',
    /* materials */
    materials_title: 'Study Materials', materials_upload: 'Upload File',
    materials_drop: 'Drop files here', materials_browse: 'or click to browse',
    materials_supported: 'PDF, images, Word, PowerPoint, Excel — max 20 MB',
    materials_uploading: 'Uploading…', materials_empty: 'No files uploaded yet',
    materials_empty_sub: 'Upload your study materials above.',
    materials_delete: 'Delete',
    /* check-in */
    checkin_title: 'Daily Check-in', checkin_date: 'Date',
    checkin_study_hours: 'Study Hours', checkin_attendance: 'Attendance %',
    checkin_completion: 'Assignment Completion %', checkin_quiz_score: 'Quiz Score (optional)',
    checkin_exam_score: 'Exam Score (optional)', checkin_sleep: 'Sleep Hours',
    checkin_stress: 'Stress Level', checkin_notes: 'Notes (optional)',
    checkin_notes_ph: 'How was your day?', checkin_submit: 'Submit Check-in',
    checkin_update: 'Update Check-in', checkin_submitting: 'Saving…',
    checkin_low: 'Low', checkin_moderate: 'Moderate', checkin_high: 'High',
    checkin_history: 'Recent Check-ins', checkin_empty: 'No check-ins yet.',
    /* predict */
    predict_title: 'Score Predictor', predict_btn: 'Predict My Score',
    predict_predicting: 'Predicting…', predict_score: 'Predicted Score',
    predict_risk: 'Risk Level', predict_recommendations: 'Recommendations',
    predict_contributions: 'Feature Impact', predict_importance: 'Feature Importance',
    predict_fill_form: 'Fill in your study data to get a prediction.',
    /* simulate */
    simulate_title: 'What-If Simulator', simulate_run: 'Run Simulation',
    simulate_running: 'Running…', simulate_reset: 'Reset to current',
    simulate_current: 'Current', simulate_hypothetical: 'Hypothetical',
    simulate_impact: 'Score Impact', simulate_no_data: 'No recent learning data found.',
    simulate_study_hours: 'Study Hours', simulate_attendance: 'Attendance',
    simulate_completion: 'Assignment Completion', simulate_quiz: 'Quiz Score',
    simulate_sleep: 'Sleep', simulate_stress: 'Stress Level',
    /* mentor */
    mentor_title: 'AI Mentor', mentor_send: 'Send',
    mentor_placeholder: 'Ask anything about your studies…',
    mentor_gen_plan: 'Generate 30-Day Plan', mentor_plan_title: 'Your 30-Day Study Plan',
    mentor_save_plan: 'Save Plan', mentor_plan_saved: 'Plan saved!',
    mentor_new_chat: 'New Chat', mentor_sessions: 'Sessions',
    mentor_generating: 'Generating…',
    /* twin */
    twin_title: 'Digital Twin', twin_health: 'Twin Health',
    twin_score: 'Overall Score', twin_trend: 'Trend',
    twin_strengths: 'Strengths', twin_improve: 'Areas to Improve',
    twin_future_30: '30-Day Projection', twin_future_60: '60-Day Projection',
    twin_future_90: '90-Day Projection', twin_no_data: 'Not enough data yet.',
    twin_log_checkin: 'Log check-ins to see your Twin evolve.',
    /* achievements */
    achievements_title: 'Achievements', achievements_earned: 'Earned',
    achievements_locked: 'Locked', achievements_empty: 'No achievements available yet.',
    /* quiz */
    quiz_title: 'AI Quiz', quiz_configure: 'Configure Your Quiz',
    quiz_powered: 'Powered by Groq AI', quiz_subject: 'Subject',
    quiz_duration: 'Duration', quiz_difficulty: 'Difficulty',
    quiz_generate: 'Generate Quiz →', quiz_history: 'Past Quizzes',
    quiz_easy: 'Easy', quiz_medium: 'Medium', quiz_hard: 'Hard',
    quiz_easy_desc: 'Basic recall & straightforward concepts',
    quiz_medium_desc: 'Applied understanding & moderate reasoning',
    quiz_hard_desc: 'Deep analysis & multi-step reasoning',
    quiz_generating: 'Generating your quiz…',
    quiz_no_subjects: 'No subjects in your profile.',
    quiz_add_subjects: 'Add subjects →',
    quiz_results_title: 'Quiz Results', quiz_correct: 'Correct',
    quiz_wrong: 'Wrong', quiz_skipped: 'Skipped', quiz_time: 'Time',
    quiz_review: 'Answer Review', quiz_take_another: 'Take Another →',
    quiz_take_another_btn: 'Take Another Quiz',
    quiz_no_history: 'No quizzes taken yet. Take your first quiz!',
    quiz_finish: 'Finish Quiz', quiz_next: 'Next Question',
  },

  hi: {
    nav_sessions: 'सत्र', nav_notes: 'नोट्स', nav_materials: 'सामग्री',
    nav_progress: 'प्रगति', nav_checkin: 'चेक-इन', nav_achievements: 'उपलब्धियां',
    nav_quiz: 'क्विज़', nav_simulate: 'सिमुलेट', nav_mentor: 'मेंटर', nav_twin: 'ट्विन',
    sign_out: 'साइन आउट', loading: 'लोड हो रहा है…', live: 'लाइव',
    save: 'सहेजें', cancel: 'रद्द करें', delete: 'हटाएं', close: 'बंद करें',
    back_dashboard: '← डैशबोर्ड',
    greeting_midnight: 'देर रात काम कर रहे हैं', greeting_morning: 'सुप्रभात',
    greeting_afternoon: 'नमस्कार', greeting_evening: 'शुभ संध्या',
    hero_sub: 'आज का दिन सार्थक बनाएं?',
    stat_sessions: 'सत्र', stat_hours: 'अध्ययन घंटे', stat_streak: 'दिन की लकीर',
    stat_notes: 'नोट्स', stat_badges: 'बैज अर्जित',
    chart_title: 'अध्ययन घंटे — पिछले 7 दिन', chart_log_today: '+ आज लॉग करें',
    chart_this_week: 'इस सप्ताह', chart_daily_avg: 'दैनिक औसत',
    no_data_title: 'अभी कोई डेटा नहीं', no_data_sub: 'चार्ट देखने के लिए पहला चेक-इन करें।',
    no_data_btn: 'आज लॉग करें →',
    quick_actions: 'त्वरित क्रियाएं',
    qa_sessions: 'सत्र', qa_materials: 'सामग्री', qa_progress: 'प्रगति',
    qa_quiz: 'क्विज़', qa_predict: 'भविष्यवाणी', qa_achievements: 'उपलब्धियां',
    qa_simulate: 'सिमुलेट', qa_mentor: 'मेंटर', qa_twin: 'ट्विन',
    qa_checkin: 'चेक-इन', qa_language: 'भाषा',
    qa_desc_study: 'अध्ययन', qa_desc_upload: 'अपलोड', qa_desc_analytics: 'विश्लेषण',
    qa_desc_quiz: 'AI क्विज़', qa_desc_ml: 'ML स्कोर', qa_desc_badges: 'बैज',
    qa_desc_whatif: 'क्या-अगर', qa_desc_advice: 'AI सलाह', qa_desc_twin: 'डिजिटल ट्विन',
    qa_desc_log: 'लॉग करें', qa_desc_language: 'बदलें',
    my_study_plan: 'मेरी अध्ययन योजना', generate_new: 'नया बनाएं →', view_full_plan: 'पूरी योजना देखें',
    no_plan_title: 'अभी कोई योजना नहीं',
    no_plan_sub: 'AI मेंटर में 30-दिवसीय योजना बनाएं।',
    go_to_mentor: 'मेंटर पर जाएं →', plan_saved: 'सहेजा गया',
    modal_plan_title: '30-दिवसीय अध्ययन योजना', modal_regenerate: 'मेंटर में दोबारा बनाएं →',
    language_title: 'भाषा चुनें', language_select: 'अपनी पसंदीदा भाषा चुनें',
    login_tagline: 'आपका AI-संचालित शैक्षणिक ट्विन', login_title: 'वापस स्वागत है',
    login_email: 'ईमेल', login_password: 'पासवर्ड', login_forgot: 'पासवर्ड भूल गए?',
    login_btn: 'साइन इन →', login_btn_loading: 'साइन इन हो रहा है…',
    login_no_account: 'अकाउंट नहीं है?', login_create: 'बनाएं',
    login_error: 'अमान्य ईमेल या पासवर्ड।',
    register_title: 'अकाउंट बनाएं', register_fullname: 'पूरा नाम',
    register_email: 'ईमेल', register_password: 'पासवर्ड',
    register_btn: 'शुरू करें →', register_btn_loading: 'अकाउंट बन रहा है…',
    register_have_account: 'पहले से अकाउंट है?', register_signin: 'साइन इन',
    register_error: 'पंजीकरण विफल। पुनः प्रयास करें।',
    forgot_title: 'पासवर्ड भूल गए', forgot_email: 'ईमेल पता',
    forgot_btn: 'रीसेट लिंक भेजें', forgot_btn_loading: 'भेज रहे हैं…',
    forgot_back: 'साइन इन पर वापस', forgot_success: 'रीसेट लिंक भेजा! इनबॉक्स देखें।',
    reset_title: 'पासवर्ड रीसेट', reset_new_pw: 'नया पासवर्ड', reset_confirm_pw: 'पासवर्ड की पुष्टि',
    reset_btn: 'पासवर्ड रीसेट', reset_btn_loading: 'रीसेट हो रहा है…', reset_mismatch: 'पासवर्ड मेल नहीं खाते।',
    profile_title: 'प्रोफ़ाइल', profile_name: 'पूरा नाम', profile_save_name: 'नाम सहेजें',
    profile_saving: 'सहेज रहे हैं…', profile_change_pw: 'पासवर्ड बदलें',
    profile_current_pw: 'वर्तमान पासवर्ड', profile_new_pw: 'नया पासवर्ड',
    profile_save_pw: 'पासवर्ड अपडेट करें', profile_avatar: 'प्रोफ़ाइल चित्र',
    profile_change_avatar: 'फ़ोटो बदलें', profile_uploading: 'अपलोड हो रहा है…',
    sessions_title: 'अध्ययन सत्र', sessions_new: '+ नया सत्र',
    sessions_create_title: 'नया अध्ययन सत्र', sessions_form_title: 'सत्र का शीर्षक',
    sessions_form_subject: 'विषय', sessions_form_subject_ph: 'विषय चुनें…',
    sessions_form_create: 'सत्र बनाएं', sessions_form_creating: 'बन रहा है…',
    sessions_form_cancel: 'रद्द करें', sessions_active: 'सक्रिय',
    sessions_completed: 'पूर्ण', sessions_mark_done: 'पूर्ण करें',
    sessions_mark_active: 'सक्रिय करें', sessions_delete: 'हटाएं',
    sessions_empty: 'अभी कोई सत्र नहीं', sessions_empty_sub: 'ऊपर पहला सत्र बनाएं।',
    notes_title: 'नोट्स', notes_new: '+ नया नोट', notes_untitled: 'शीर्षकहीन नोट',
    notes_placeholder: 'लिखना शुरू करें…', notes_save: 'सहेजें',
    notes_saving: 'सहेज रहे हैं…', notes_saved: 'सहेजा ✓', notes_delete: 'हटाएं',
    notes_empty: 'अभी कोई नोट नहीं', notes_empty_sub: 'शुरू करने के लिए नोट बनाएं।',
    materials_title: 'अध्ययन सामग्री', materials_upload: 'फ़ाइल अपलोड करें',
    materials_drop: 'यहाँ फ़ाइलें छोड़ें', materials_browse: 'या ब्राउज़ करने के लिए क्लिक करें',
    materials_supported: 'PDF, चित्र, Word, PowerPoint, Excel — अधिकतम 20 MB',
    materials_uploading: 'अपलोड हो रहा है…', materials_empty: 'अभी कोई फ़ाइल नहीं',
    materials_empty_sub: 'ऊपर अपनी सामग्री अपलोड करें।', materials_delete: 'हटाएं',
    checkin_title: 'दैनिक चेक-इन', checkin_date: 'दिनांक',
    checkin_study_hours: 'अध्ययन घंटे', checkin_attendance: 'उपस्थिति %',
    checkin_completion: 'असाइनमेंट पूर्णता %', checkin_quiz_score: 'क्विज़ स्कोर (वैकल्पिक)',
    checkin_exam_score: 'परीक्षा स्कोर (वैकल्पिक)', checkin_sleep: 'नींद के घंटे',
    checkin_stress: 'तनाव स्तर', checkin_notes: 'नोट्स (वैकल्पिक)',
    checkin_notes_ph: 'आपका दिन कैसा था?', checkin_submit: 'चेक-इन सबमिट करें',
    checkin_update: 'चेक-इन अपडेट करें', checkin_submitting: 'सहेज रहे हैं…',
    checkin_low: 'कम', checkin_moderate: 'मध्यम', checkin_high: 'उच्च',
    checkin_history: 'हाल के चेक-इन', checkin_empty: 'अभी कोई चेक-इन नहीं।',
    predict_title: 'स्कोर भविष्यवक्ता', predict_btn: 'मेरा स्कोर भविष्यवाणी करें',
    predict_predicting: 'भविष्यवाणी हो रही है…', predict_score: 'अनुमानित स्कोर',
    predict_risk: 'जोखिम स्तर', predict_recommendations: 'सिफारिशें',
    predict_contributions: 'विशेषता प्रभाव', predict_importance: 'विशेषता महत्व',
    predict_fill_form: 'अनुमान के लिए अपना अध्ययन डेटा भरें।',
    simulate_title: 'क्या-अगर सिमुलेटर', simulate_run: 'सिमुलेशन चलाएं',
    simulate_running: 'चल रहा है…', simulate_reset: 'वर्तमान पर रीसेट',
    simulate_current: 'वर्तमान', simulate_hypothetical: 'काल्पनिक',
    simulate_impact: 'स्कोर प्रभाव', simulate_no_data: 'कोई हालिया डेटा नहीं।',
    simulate_study_hours: 'अध्ययन घंटे', simulate_attendance: 'उपस्थिति',
    simulate_completion: 'असाइनमेंट पूर्णता', simulate_quiz: 'क्विज़ स्कोर',
    simulate_sleep: 'नींद', simulate_stress: 'तनाव स्तर',
    mentor_title: 'AI मेंटर', mentor_send: 'भेजें',
    mentor_placeholder: 'अपनी पढ़ाई के बारे में कुछ भी पूछें…',
    mentor_gen_plan: '30-दिवसीय योजना बनाएं', mentor_plan_title: 'आपकी 30-दिवसीय योजना',
    mentor_save_plan: 'योजना सहेजें', mentor_plan_saved: 'योजना सहेजी!',
    mentor_new_chat: 'नई चैट', mentor_sessions: 'सत्र', mentor_generating: 'बन रहा है…',
    twin_title: 'डिजिटल ट्विन', twin_health: 'ट्विन स्वास्थ्य',
    twin_score: 'समग्र स्कोर', twin_trend: 'प्रवृत्ति',
    twin_strengths: 'ताकत', twin_improve: 'सुधार के क्षेत्र',
    twin_future_30: '30-दिन का अनुमान', twin_future_60: '60-दिन का अनुमान',
    twin_future_90: '90-दिन का अनुमान', twin_no_data: 'अभी पर्याप्त डेटा नहीं।',
    twin_log_checkin: 'अपने ट्विन को विकसित होते देखने के लिए चेक-इन करें।',
    achievements_title: 'उपलब्धियां', achievements_earned: 'अर्जित',
    achievements_locked: 'बंद', achievements_empty: 'अभी कोई उपलब्धि नहीं।',
    quiz_title: 'AI क्विज़', quiz_configure: 'अपना क्विज़ कॉन्फ़िगर करें',
    quiz_powered: 'Groq AI द्वारा संचालित', quiz_subject: 'विषय',
    quiz_duration: 'अवधि', quiz_difficulty: 'कठिनाई',
    quiz_generate: 'क्विज़ बनाएं →', quiz_history: 'पिछले क्विज़',
    quiz_easy: 'आसान', quiz_medium: 'मध्यम', quiz_hard: 'कठिन',
    quiz_easy_desc: 'बुनियादी याद और सीधी अवधारणाएं',
    quiz_medium_desc: 'व्यावहारिक समझ और मध्यम तर्क',
    quiz_hard_desc: 'गहरा विश्लेषण और बहु-चरणीय तर्क',
    quiz_generating: 'आपका क्विज़ बन रहा है…',
    quiz_no_subjects: 'प्रोफ़ाइल में कोई विषय नहीं।', quiz_add_subjects: 'विषय जोड़ें →',
    quiz_results_title: 'क्विज़ परिणाम', quiz_correct: 'सही',
    quiz_wrong: 'गलत', quiz_skipped: 'छोड़ा', quiz_time: 'समय',
    quiz_review: 'उत्तर समीक्षा', quiz_take_another: 'दूसरा लें →',
    quiz_take_another_btn: 'दूसरा क्विज़ लें',
    quiz_no_history: 'अभी कोई क्विज़ नहीं लिया। पहला लें!',
    quiz_finish: 'क्विज़ समाप्त', quiz_next: 'अगला प्रश्न',
  },

  bn: {
    nav_sessions: 'সেশন', nav_notes: 'নোট', nav_materials: 'উপকরণ',
    nav_progress: 'অগ্রগতি', nav_checkin: 'চেক-ইন', nav_achievements: 'অর্জন',
    nav_quiz: 'কুইজ', nav_simulate: 'সিমুলেট', nav_mentor: 'মেন্টর', nav_twin: 'টুইন',
    sign_out: 'সাইন আউট', loading: 'লোড হচ্ছে…', live: 'লাইভ',
    save: 'সংরক্ষণ', cancel: 'বাতিল', delete: 'মুছুন', close: 'বন্ধ',
    back_dashboard: '← ড্যাশবোর্ড',
    greeting_midnight: 'রাত জেগে কাজ করছেন', greeting_morning: 'শুভ সকাল',
    greeting_afternoon: 'শুভ দুপুর', greeting_evening: 'শুভ সন্ধ্যা',
    hero_sub: 'আজকের দিনটি অর্থবহ করুন?',
    stat_sessions: 'সেশন', stat_hours: 'পড়ার ঘণ্টা', stat_streak: 'ধারাবাহিক দিন',
    stat_notes: 'নোট', stat_badges: 'অর্জিত ব্যাজ',
    chart_title: 'পড়ার ঘণ্টা — গত ৭ দিন', chart_log_today: '+ আজ লগ করুন',
    chart_this_week: 'এই সপ্তাহ', chart_daily_avg: 'দৈনিক গড়',
    no_data_title: 'এখনও কোনো ডেটা নেই', no_data_sub: 'চার্ট দেখতে প্রথম চেক-ইন করুন।',
    no_data_btn: 'আজ লগ করুন →',
    quick_actions: 'দ্রুত ক্রিয়া',
    qa_sessions: 'সেশন', qa_materials: 'উপকরণ', qa_progress: 'অগ্রগতি',
    qa_quiz: 'কুইজ', qa_predict: 'পূর্বাভাস', qa_achievements: 'অর্জন',
    qa_simulate: 'সিমুলেট', qa_mentor: 'মেন্টর', qa_twin: 'টুইন',
    qa_checkin: 'চেক-ইন', qa_language: 'ভাষা',
    qa_desc_study: 'পড়াশোনা', qa_desc_upload: 'আপলোড', qa_desc_analytics: 'বিশ্লেষণ',
    qa_desc_quiz: 'AI কুইজ', qa_desc_ml: 'ML স্কোর', qa_desc_badges: 'ব্যাজ',
    qa_desc_whatif: 'কি-যদি', qa_desc_advice: 'AI পরামর্শ', qa_desc_twin: 'ডিজিটাল টুইন',
    qa_desc_log: 'আজ লগ করুন', qa_desc_language: 'পরিবর্তন',
    my_study_plan: 'আমার পড়ার পরিকল্পনা', generate_new: 'নতুন তৈরি করুন →',
    view_full_plan: 'সম্পূর্ণ পরিকল্পনা দেখুন',
    no_plan_title: 'এখনও কোনো পরিকল্পনা নেই',
    no_plan_sub: 'AI মেন্টরে ৩০ দিনের পরিকল্পনা তৈরি করুন।',
    go_to_mentor: 'মেন্টরে যান →', plan_saved: 'সংরক্ষিত',
    modal_plan_title: '৩০-দিনের পড়ার পরিকল্পনা', modal_regenerate: 'মেন্টরে পুনরায় তৈরি করুন →',
    language_title: 'ভাষা বেছে নিন', language_select: 'আপনার পছন্দের ভাষা বেছে নিন',
    login_tagline: 'আপনার AI-চালিত শিক্ষা সহকারী', login_title: 'স্বাগতম',
    login_email: 'ইমেইল', login_password: 'পাসওয়ার্ড', login_forgot: 'পাসওয়ার্ড ভুলেছেন?',
    login_btn: 'সাইন ইন →', login_btn_loading: 'সাইন ইন হচ্ছে…',
    login_no_account: 'অ্যাকাউন্ট নেই?', login_create: 'তৈরি করুন',
    login_error: 'ভুল ইমেইল বা পাসওয়ার্ড।',
    register_title: 'অ্যাকাউন্ট তৈরি করুন', register_fullname: 'পুরো নাম',
    register_email: 'ইমেইল', register_password: 'পাসওয়ার্ড',
    register_btn: 'শুরু করুন →', register_btn_loading: 'অ্যাকাউন্ট তৈরি হচ্ছে…',
    register_have_account: 'ইতিমধ্যে অ্যাকাউন্ট আছে?', register_signin: 'সাইন ইন',
    register_error: 'নিবন্ধন ব্যর্থ। আবার চেষ্টা করুন।',
    forgot_title: 'পাসওয়ার্ড ভুলেছেন', forgot_email: 'ইমেইল ঠিকানা',
    forgot_btn: 'রিসেট লিংক পাঠান', forgot_btn_loading: 'পাঠানো হচ্ছে…',
    forgot_back: 'সাইন ইনে ফিরুন', forgot_success: 'রিসেট লিংক পাঠানো হয়েছে!',
    reset_title: 'পাসওয়ার্ড রিসেট', reset_new_pw: 'নতুন পাসওয়ার্ড',
    reset_confirm_pw: 'পাসওয়ার্ড নিশ্চিত করুন',
    reset_btn: 'পাসওয়ার্ড রিসেট', reset_btn_loading: 'রিসেট হচ্ছে…',
    reset_mismatch: 'পাসওয়ার্ড মেলেনি।',
    profile_title: 'প্রোফাইল', profile_name: 'পুরো নাম', profile_save_name: 'নাম সংরক্ষণ',
    profile_saving: 'সংরক্ষণ হচ্ছে…', profile_change_pw: 'পাসওয়ার্ড পরিবর্তন',
    profile_current_pw: 'বর্তমান পাসওয়ার্ড', profile_new_pw: 'নতুন পাসওয়ার্ড',
    profile_save_pw: 'পাসওয়ার্ড আপডেট', profile_avatar: 'প্রোফাইল ছবি',
    profile_change_avatar: 'ছবি পরিবর্তন', profile_uploading: 'আপলোড হচ্ছে…',
    sessions_title: 'পড়ার সেশন', sessions_new: '+ নতুন সেশন',
    sessions_create_title: 'নতুন পড়ার সেশন', sessions_form_title: 'সেশনের শিরোনাম',
    sessions_form_subject: 'বিষয়', sessions_form_subject_ph: 'বিষয় বেছে নিন…',
    sessions_form_create: 'সেশন তৈরি', sessions_form_creating: 'তৈরি হচ্ছে…',
    sessions_form_cancel: 'বাতিল', sessions_active: 'সক্রিয়',
    sessions_completed: 'সম্পন্ন', sessions_mark_done: 'সম্পন্ন করুন',
    sessions_mark_active: 'সক্রিয় করুন', sessions_delete: 'মুছুন',
    sessions_empty: 'এখনও কোনো সেশন নেই', sessions_empty_sub: 'প্রথম সেশন তৈরি করুন।',
    notes_title: 'নোট', notes_new: '+ নতুন নোট', notes_untitled: 'শিরোনামহীন নোট',
    notes_placeholder: 'লেখা শুরু করুন…', notes_save: 'সংরক্ষণ',
    notes_saving: 'সংরক্ষণ হচ্ছে…', notes_saved: 'সংরক্ষিত ✓', notes_delete: 'মুছুন',
    notes_empty: 'এখনও কোনো নোট নেই', notes_empty_sub: 'শুরু করতে নোট তৈরি করুন।',
    materials_title: 'পড়ার উপকরণ', materials_upload: 'ফাইল আপলোড',
    materials_drop: 'এখানে ফাইল ছাড়ুন', materials_browse: 'বা ক্লিক করুন',
    materials_supported: 'PDF, ছবি, Word, PowerPoint, Excel — সর্বোচ্চ 20 MB',
    materials_uploading: 'আপলোড হচ্ছে…', materials_empty: 'এখনও কোনো ফাইল নেই',
    materials_empty_sub: 'উপকরণ আপলোড করুন।', materials_delete: 'মুছুন',
    checkin_title: 'দৈনিক চেক-ইন', checkin_date: 'তারিখ',
    checkin_study_hours: 'পড়ার ঘণ্টা', checkin_attendance: 'উপস্থিতি %',
    checkin_completion: 'অ্যাসাইনমেন্ট সম্পন্নতা %', checkin_quiz_score: 'কুইজ স্কোর (ঐচ্ছিক)',
    checkin_exam_score: 'পরীক্ষার স্কোর (ঐচ্ছিক)', checkin_sleep: 'ঘুমের ঘণ্টা',
    checkin_stress: 'মানসিক চাপের মাত্রা', checkin_notes: 'নোট (ঐচ্ছিক)',
    checkin_notes_ph: 'আপনার দিন কেমন ছিল?', checkin_submit: 'চেক-ইন জমা দিন',
    checkin_update: 'চেক-ইন আপডেট', checkin_submitting: 'সংরক্ষণ হচ্ছে…',
    checkin_low: 'কম', checkin_moderate: 'মাঝারি', checkin_high: 'বেশি',
    checkin_history: 'সাম্প্রতিক চেক-ইন', checkin_empty: 'এখনও কোনো চেক-ইন নেই।',
    predict_title: 'স্কোর পূর্বাভাস', predict_btn: 'আমার স্কোর পূর্বাভাস করুন',
    predict_predicting: 'পূর্বাভাস হচ্ছে…', predict_score: 'আনুমানিক স্কোর',
    predict_risk: 'ঝুঁকির মাত্রা', predict_recommendations: 'সুপারিশ',
    predict_contributions: 'বৈশিষ্ট্য প্রভাব', predict_importance: 'বৈশিষ্ট্য গুরুত্ব',
    predict_fill_form: 'পূর্বাভাসের জন্য ডেটা পূরণ করুন।',
    simulate_title: 'কি-যদি সিমুলেটর', simulate_run: 'সিমুলেশন চালান',
    simulate_running: 'চলছে…', simulate_reset: 'বর্তমানে রিসেট',
    simulate_current: 'বর্তমান', simulate_hypothetical: 'কাল্পনিক',
    simulate_impact: 'স্কোর প্রভাব', simulate_no_data: 'কোনো সাম্প্রতিক ডেটা নেই।',
    simulate_study_hours: 'পড়ার ঘণ্টা', simulate_attendance: 'উপস্থিতি',
    simulate_completion: 'অ্যাসাইনমেন্ট সম্পন্নতা', simulate_quiz: 'কুইজ স্কোর',
    simulate_sleep: 'ঘুম', simulate_stress: 'মানসিক চাপ',
    mentor_title: 'AI মেন্টর', mentor_send: 'পাঠান',
    mentor_placeholder: 'পড়াশোনা সম্পর্কে যেকোনো প্রশ্ন করুন…',
    mentor_gen_plan: '৩০ দিনের পরিকল্পনা তৈরি করুন', mentor_plan_title: 'আপনার ৩০ দিনের পরিকল্পনা',
    mentor_save_plan: 'পরিকল্পনা সংরক্ষণ', mentor_plan_saved: 'পরিকল্পনা সংরক্ষিত!',
    mentor_new_chat: 'নতুন চ্যাট', mentor_sessions: 'সেশন', mentor_generating: 'তৈরি হচ্ছে…',
    twin_title: 'ডিজিটাল টুইন', twin_health: 'টুইন স্বাস্থ্য',
    twin_score: 'সামগ্রিক স্কোর', twin_trend: 'প্রবণতা',
    twin_strengths: 'শক্তি', twin_improve: 'উন্নতির ক্ষেত্র',
    twin_future_30: '৩০ দিনের পূর্বাভাস', twin_future_60: '৬০ দিনের পূর্বাভাস',
    twin_future_90: '৯০ দিনের পূর্বাভাস', twin_no_data: 'এখনও পর্যাপ্ত ডেটা নেই।',
    twin_log_checkin: 'টুইন বিকশিত হতে দেখতে চেক-ইন করুন।',
    achievements_title: 'অর্জন', achievements_earned: 'অর্জিত',
    achievements_locked: 'বন্ধ', achievements_empty: 'এখনও কোনো অর্জন নেই।',
    quiz_title: 'AI কুইজ', quiz_configure: 'আপনার কুইজ কনফিগার করুন',
    quiz_powered: 'Groq AI দ্বারা চালিত', quiz_subject: 'বিষয়',
    quiz_duration: 'সময়কাল', quiz_difficulty: 'কঠিনতা',
    quiz_generate: 'কুইজ তৈরি করুন →', quiz_history: 'আগের কুইজ',
    quiz_easy: 'সহজ', quiz_medium: 'মাঝারি', quiz_hard: 'কঠিন',
    quiz_easy_desc: 'মৌলিক মনে রাখা ও সহজ ধারণা',
    quiz_medium_desc: 'ব্যবহারিক বোঝাপড়া ও মাঝারি যুক্তি',
    quiz_hard_desc: 'গভীর বিশ্লেষণ ও বহু-ধাপের যুক্তি',
    quiz_generating: 'আপনার কুইজ তৈরি হচ্ছে…',
    quiz_no_subjects: 'প্রোফাইলে কোনো বিষয় নেই।', quiz_add_subjects: 'বিষয় যোগ করুন →',
    quiz_results_title: 'কুইজ ফলাফল', quiz_correct: 'সঠিক',
    quiz_wrong: 'ভুল', quiz_skipped: 'এড়িয়ে গেছেন', quiz_time: 'সময়',
    quiz_review: 'উত্তর পর্যালোচনা', quiz_take_another: 'আরেকটি নিন →',
    quiz_take_another_btn: 'আরেকটি কুইজ নিন',
    quiz_no_history: 'এখনও কোনো কুইজ নেওয়া হয়নি।',
    quiz_finish: 'কুইজ শেষ', quiz_next: 'পরবর্তী প্রশ্ন',
  },

  ta: {
    nav_sessions: 'அமர்வுகள்', nav_notes: 'குறிப்புகள்', nav_materials: 'பொருட்கள்',
    nav_progress: 'முன்னேற்றம்', nav_checkin: 'செக்-இன்', nav_achievements: 'சாதனைகள்',
    nav_quiz: 'வினாடி வினா', nav_simulate: 'உருவகப்படுத்து', nav_mentor: 'வழிகாட்டி', nav_twin: 'இரட்டை',
    sign_out: 'வெளியேறு', loading: 'ஏற்றுகிறது…', live: 'நேரலை',
    save: 'சேமி', cancel: 'ரத்து', delete: 'நீக்கு', close: 'மூடு',
    back_dashboard: '← டாஷ்போர்டு',
    greeting_midnight: 'இரவு நேர உழைப்பு', greeting_morning: 'காலை வணக்கம்',
    greeting_afternoon: 'மதிய வணக்கம்', greeting_evening: 'மாலை வணக்கம்',
    hero_sub: 'இன்றை நாளை அர்த்தமுள்ளதாக்குங்கள்?',
    stat_sessions: 'அமர்வுகள்', stat_hours: 'படிக்கும் மணிநேரம்', stat_streak: 'தொடர் நாட்கள்',
    stat_notes: 'குறிப்புகள்', stat_badges: 'பெற்ற பதக்கங்கள்',
    chart_title: 'படிக்கும் நேரம் — கடந்த 7 நாட்கள்', chart_log_today: '+ இன்று பதிவு',
    chart_this_week: 'இந்த வாரம்', chart_daily_avg: 'நாள் சராசரி',
    no_data_title: 'இன்னும் தரவு இல்லை', no_data_sub: 'சார்ட் பார்க்க முதல் செக்-இன் செய்யுங்கள்.',
    no_data_btn: 'இன்று பதிவு →',
    quick_actions: 'விரைவு செயல்கள்',
    qa_sessions: 'அமர்வுகள்', qa_materials: 'பொருட்கள்', qa_progress: 'முன்னேற்றம்',
    qa_quiz: 'வினா', qa_predict: 'கணிப்பு', qa_achievements: 'சாதனைகள்',
    qa_simulate: 'உருவகம்', qa_mentor: 'வழிகாட்டி', qa_twin: 'இரட்டை',
    qa_checkin: 'செக்-இன்', qa_language: 'மொழி',
    qa_desc_study: 'படிப்பு', qa_desc_upload: 'பதிவேற்றம்', qa_desc_analytics: 'பகுப்பாய்வு',
    qa_desc_quiz: 'AI வினா', qa_desc_ml: 'ML மதிப்பு', qa_desc_badges: 'பதக்கங்கள்',
    qa_desc_whatif: 'என்னாகும்', qa_desc_advice: 'AI ஆலோசனை', qa_desc_twin: 'டிஜிட்டல் இரட்டை',
    qa_desc_log: 'பதிவு செய்', qa_desc_language: 'மாற்று',
    my_study_plan: 'என் படிப்பு திட்டம்', generate_new: 'புதிது உருவாக்கு →',
    view_full_plan: 'முழு திட்டம் பார்',
    no_plan_title: 'இன்னும் திட்டம் இல்லை',
    no_plan_sub: 'AI வழிகாட்டியில் 30 நாள் திட்டம் உருவாக்கு.',
    go_to_mentor: 'வழிகாட்டிக்கு செல் →', plan_saved: 'சேமிக்கப்பட்டது',
    modal_plan_title: '30-நாள் படிப்பு திட்டம்', modal_regenerate: 'வழிகாட்டியில் மீண்டும் உருவாக்கு →',
    language_title: 'மொழி தேர்வு', language_select: 'உங்கள் விருப்பமான மொழியை தேர்வு செய்யுங்கள்',
    login_tagline: 'உங்கள் AI-இயக்கப்படும் கல்வி இரட்டை', login_title: 'மீண்டும் வரவேற்கிறோம்',
    login_email: 'மின்னஞ்சல்', login_password: 'கடவுச்சொல்', login_forgot: 'கடவுச்சொல் மறந்தீர்களா?',
    login_btn: 'உள்நுழை →', login_btn_loading: 'உள்நுழைகிறது…',
    login_no_account: 'கணக்கு இல்லையா?', login_create: 'உருவாக்கு',
    login_error: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
    register_title: 'கணக்கு உருவாக்கு', register_fullname: 'முழு பெயர்',
    register_email: 'மின்னஞ்சல்', register_password: 'கடவுச்சொல்',
    register_btn: 'தொடங்கு →', register_btn_loading: 'கணக்கு உருவாகிறது…',
    register_have_account: 'ஏற்கனவே கணக்கு உள்ளதா?', register_signin: 'உள்நுழை',
    register_error: 'பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    forgot_title: 'கடவுச்சொல் மறந்தது', forgot_email: 'மின்னஞ்சல் முகவரி',
    forgot_btn: 'மீட்டமைப்பு இணைப்பு அனுப்பு', forgot_btn_loading: 'அனுப்புகிறது…',
    forgot_back: 'உள்நுழைவுக்கு திரும்பு', forgot_success: 'மீட்டமைப்பு இணைப்பு அனுப்பப்பட்டது!',
    reset_title: 'கடவுச்சொல் மீட்டமை', reset_new_pw: 'புதிய கடவுச்சொல்',
    reset_confirm_pw: 'கடவுச்சொல் உறுதிப்படுத்து',
    reset_btn: 'கடவுச்சொல் மீட்டமை', reset_btn_loading: 'மீட்டமைக்கிறது…',
    reset_mismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை.',
    profile_title: 'சுயவிவரம்', profile_name: 'முழு பெயர்', profile_save_name: 'பெயர் சேமி',
    profile_saving: 'சேமிக்கிறது…', profile_change_pw: 'கடவுச்சொல் மாற்று',
    profile_current_pw: 'தற்போதைய கடவுச்சொல்', profile_new_pw: 'புதிய கடவுச்சொல்',
    profile_save_pw: 'கடவுச்சொல் புதுப்பி', profile_avatar: 'சுயவிவர படம்',
    profile_change_avatar: 'படம் மாற்று', profile_uploading: 'பதிவேற்றுகிறது…',
    sessions_title: 'படிப்பு அமர்வுகள்', sessions_new: '+ புதிய அமர்வு',
    sessions_create_title: 'புதிய படிப்பு அமர்வு', sessions_form_title: 'அமர்வு தலைப்பு',
    sessions_form_subject: 'பாடம்', sessions_form_subject_ph: 'பாடம் தேர்வு…',
    sessions_form_create: 'அமர்வு உருவாக்கு', sessions_form_creating: 'உருவாகிறது…',
    sessions_form_cancel: 'ரத்து', sessions_active: 'செயலில்',
    sessions_completed: 'முடிந்தது', sessions_mark_done: 'முடிந்தது என குறி',
    sessions_mark_active: 'செயலில் என குறி', sessions_delete: 'நீக்கு',
    sessions_empty: 'இன்னும் அமர்வு இல்லை', sessions_empty_sub: 'முதல் அமர்வை உருவாக்கு.',
    notes_title: 'குறிப்புகள்', notes_new: '+ புதிய குறிப்பு', notes_untitled: 'தலைப்பற்ற குறிப்பு',
    notes_placeholder: 'எழுதத் தொடங்கு…', notes_save: 'சேமி',
    notes_saving: 'சேமிக்கிறது…', notes_saved: 'சேமிக்கப்பட்டது ✓', notes_delete: 'நீக்கு',
    notes_empty: 'இன்னும் குறிப்பு இல்லை', notes_empty_sub: 'தொடங்க குறிப்பு உருவாக்கு.',
    materials_title: 'படிப்பு பொருட்கள்', materials_upload: 'கோப்பு பதிவேற்று',
    materials_drop: 'கோப்புகளை இங்கே விடு', materials_browse: 'அல்லது கிளிக் செய்',
    materials_supported: 'PDF, படங்கள், Word, PowerPoint, Excel — அதிகபட்சம் 20 MB',
    materials_uploading: 'பதிவேற்றுகிறது…', materials_empty: 'இன்னும் கோப்பு இல்லை',
    materials_empty_sub: 'உங்கள் பொருட்களை பதிவேற்றுங்கள்.', materials_delete: 'நீக்கு',
    checkin_title: 'தினசரி செக்-இன்', checkin_date: 'தேதி',
    checkin_study_hours: 'படிக்கும் மணிநேரம்', checkin_attendance: 'வருகை %',
    checkin_completion: 'பணி முடிவு %', checkin_quiz_score: 'வினா மதிப்பெண் (விருப்பம்)',
    checkin_exam_score: 'தேர்வு மதிப்பெண் (விருப்பம்)', checkin_sleep: 'தூக்க மணிநேரம்',
    checkin_stress: 'மன அழுத்த நிலை', checkin_notes: 'குறிப்புகள் (விருப்பம்)',
    checkin_notes_ph: 'உங்கள் நாள் எப்படி இருந்தது?', checkin_submit: 'செக்-இன் சமர்ப்பி',
    checkin_update: 'செக்-இன் புதுப்பி', checkin_submitting: 'சேமிக்கிறது…',
    checkin_low: 'குறைவு', checkin_moderate: 'மிதமான', checkin_high: 'அதிகம்',
    checkin_history: 'சமீபத்திய செக்-இன்', checkin_empty: 'இன்னும் செக்-இன் இல்லை.',
    predict_title: 'மதிப்பெண் கணிப்பு', predict_btn: 'என் மதிப்பெண் கணி',
    predict_predicting: 'கணிக்கிறது…', predict_score: 'கணிக்கப்பட்ட மதிப்பெண்',
    predict_risk: 'ஆபத்து நிலை', predict_recommendations: 'பரிந்துரைகள்',
    predict_contributions: 'அம்சம் தாக்கம்', predict_importance: 'அம்சம் முக்கியத்துவம்',
    predict_fill_form: 'கணிப்புக்கு உங்கள் தரவை நிரப்புங்கள்.',
    simulate_title: 'என்னாகும் சிமுலேட்டர்', simulate_run: 'சிமுலேஷன் இயக்கு',
    simulate_running: 'இயங்குகிறது…', simulate_reset: 'தற்போதையதுக்கு மீட்டமை',
    simulate_current: 'தற்போதைய', simulate_hypothetical: 'கற்பனையான',
    simulate_impact: 'மதிப்பெண் தாக்கம்', simulate_no_data: 'சமீபத்திய தரவு இல்லை.',
    simulate_study_hours: 'படிக்கும் நேரம்', simulate_attendance: 'வருகை',
    simulate_completion: 'பணி முடிவு', simulate_quiz: 'வினா மதிப்பெண்',
    simulate_sleep: 'தூக்கம்', simulate_stress: 'மன அழுத்தம்',
    mentor_title: 'AI வழிகாட்டி', mentor_send: 'அனுப்பு',
    mentor_placeholder: 'படிப்பு பற்றி எதுவும் கேளுங்கள்…',
    mentor_gen_plan: '30 நாள் திட்டம் உருவாக்கு', mentor_plan_title: 'உங்கள் 30 நாள் திட்டம்',
    mentor_save_plan: 'திட்டம் சேமி', mentor_plan_saved: 'திட்டம் சேமிக்கப்பட்டது!',
    mentor_new_chat: 'புதிய அரட்டை', mentor_sessions: 'அமர்வுகள்', mentor_generating: 'உருவாகிறது…',
    twin_title: 'டிஜிட்டல் இரட்டை', twin_health: 'இரட்டை ஆரோக்கியம்',
    twin_score: 'ஒட்டுமொத்த மதிப்பெண்', twin_trend: 'போக்கு',
    twin_strengths: 'பலங்கள்', twin_improve: 'மேம்பட வேண்டிய பகுதிகள்',
    twin_future_30: '30 நாள் கணிப்பு', twin_future_60: '60 நாள் கணிப்பு',
    twin_future_90: '90 நாள் கணிப்பு', twin_no_data: 'இன்னும் போதுமான தரவு இல்லை.',
    twin_log_checkin: 'இரட்டை வளர்வதை காண செக்-இன் செய்யுங்கள்.',
    achievements_title: 'சாதனைகள்', achievements_earned: 'பெற்றது',
    achievements_locked: 'பூட்டப்பட்டது', achievements_empty: 'இன்னும் சாதனை இல்லை.',
    quiz_title: 'AI வினாடி வினா', quiz_configure: 'உங்கள் வினாவை அமைக்கவும்',
    quiz_powered: 'Groq AI ஆல் இயக்கப்படுகிறது', quiz_subject: 'பாடம்',
    quiz_duration: 'கால அளவு', quiz_difficulty: 'கடினத்தன்மை',
    quiz_generate: 'வினா உருவாக்கு →', quiz_history: 'முந்தைய வினாக்கள்',
    quiz_easy: 'எளிது', quiz_medium: 'நடுத்தரம்', quiz_hard: 'கடினம்',
    quiz_easy_desc: 'அடிப்படை நினைவு மற்றும் எளிய கருத்துகள்',
    quiz_medium_desc: 'பயன்பாட்டு புரிதல் மற்றும் நடுத்தர தர்க்கம்',
    quiz_hard_desc: 'ஆழமான பகுப்பாய்வு மற்றும் பல படி தர்க்கம்',
    quiz_generating: 'உங்கள் வினா உருவாகிறது…',
    quiz_no_subjects: 'சுயவிவரத்தில் பாடம் இல்லை.', quiz_add_subjects: 'பாடம் சேர் →',
    quiz_results_title: 'வினா முடிவுகள்', quiz_correct: 'சரி',
    quiz_wrong: 'தவறு', quiz_skipped: 'தவிர்க்கப்பட்டது', quiz_time: 'நேரம்',
    quiz_review: 'விடை மதிப்பாய்வு', quiz_take_another: 'மற்றொன்று எடு →',
    quiz_take_another_btn: 'மற்றொரு வினா எடு',
    quiz_no_history: 'இன்னும் வினா எடுக்கவில்லை.',
    quiz_finish: 'வினா முடி', quiz_next: 'அடுத்த கேள்வி',
  },

  te: {
    nav_sessions: 'సెషన్లు', nav_notes: 'నోట్స్', nav_materials: 'పదార్థాలు',
    nav_progress: 'పురోగతి', nav_checkin: 'చెక్-ఇన్', nav_achievements: 'విజయాలు',
    nav_quiz: 'క్విజ్', nav_simulate: 'అనుకరించు', nav_mentor: 'మెంటర్', nav_twin: 'ట్విన్',
    sign_out: 'సైన్ అవుట్', loading: 'లోడ్ అవుతోంది…', live: 'లైవ్',
    save: 'సేవ్', cancel: 'రద్దు', delete: 'తొలగించు', close: 'మూసివేయి',
    back_dashboard: '← డాష్‌బోర్డ్',
    greeting_midnight: 'అర్ధరాత్రి పని చేస్తున్నారు', greeting_morning: 'శుభోదయం',
    greeting_afternoon: 'నమస్కారం', greeting_evening: 'శుభ సాయంత్రం',
    hero_sub: 'ఈ రోజును సార్థకం చేసుకుందాం?',
    stat_sessions: 'సెషన్లు', stat_hours: 'చదువు గంటలు', stat_streak: 'రోజుల వరుస',
    stat_notes: 'నోట్స్', stat_badges: 'సంపాదించిన బ్యాడ్జ్‌లు',
    chart_title: 'చదువు గంటలు — గత 7 రోజులు', chart_log_today: '+ ఈ రోజు లాగ్',
    chart_this_week: 'ఈ వారం', chart_daily_avg: 'రోజువారీ సగటు',
    no_data_title: 'ఇంకా డేటా లేదు', no_data_sub: 'చార్ట్ చూడటానికి మొదటి చెక్-ఇన్ చేయండి.',
    no_data_btn: 'ఈ రోజు లాగ్ →',
    quick_actions: 'త్వరిత చర్యలు',
    qa_sessions: 'సెషన్లు', qa_materials: 'పదార్థాలు', qa_progress: 'పురోగతి',
    qa_quiz: 'క్విజ్', qa_predict: 'అంచనా', qa_achievements: 'విజయాలు',
    qa_simulate: 'అనుకరించు', qa_mentor: 'మెంటర్', qa_twin: 'ట్విన్',
    qa_checkin: 'చెక్-ఇన్', qa_language: 'భాష',
    qa_desc_study: 'చదువు', qa_desc_upload: 'అప్‌లోడ్', qa_desc_analytics: 'విశ్లేషణ',
    qa_desc_quiz: 'AI క్విజ్', qa_desc_ml: 'ML స్కోర్', qa_desc_badges: 'బ్యాడ్జ్‌లు',
    qa_desc_whatif: 'ఏమవుతుంది', qa_desc_advice: 'AI సలహా', qa_desc_twin: 'డిజిటల్ ట్విన్',
    qa_desc_log: 'లాగ్ చేయి', qa_desc_language: 'మార్చు',
    my_study_plan: 'నా చదువు ప్రణాళిక', generate_new: 'కొత్తది రూపొందించు →',
    view_full_plan: 'పూర్తి ప్రణాళిక చూడు',
    no_plan_title: 'ఇంకా ప్రణాళిక లేదు',
    no_plan_sub: 'AI మెంటర్‌లో 30 రోజుల ప్రణాళిక రూపొందించండి.',
    go_to_mentor: 'మెంటర్‌కు వెళ్ళు →', plan_saved: 'సేవ్ అయింది',
    modal_plan_title: '30-రోజుల చదువు ప్రణాళిక', modal_regenerate: 'మెంటర్‌లో మళ్ళీ రూపొందించు →',
    language_title: 'భాష ఎంచుకోండి', language_select: 'మీకు ఇష్టమైన భాష ఎంచుకోండి',
    login_tagline: 'మీ AI-శక్తితో నడిచే విద్యా ట్విన్', login_title: 'తిరిగి స్వాగతం',
    login_email: 'ఇమెయిల్', login_password: 'పాస్‌వర్డ్', login_forgot: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    login_btn: 'సైన్ ఇన్ →', login_btn_loading: 'సైన్ ఇన్ అవుతోంది…',
    login_no_account: 'అకౌంట్ లేదా?', login_create: 'తయారుచేయి',
    login_error: 'తప్పు ఇమెయిల్ లేదా పాస్‌వర్డ్.',
    register_title: 'అకౌంట్ తయారుచేయి', register_fullname: 'పూర్తి పేరు',
    register_email: 'ఇమెయిల్', register_password: 'పాస్‌వర్డ్',
    register_btn: 'ప్రారంభించు →', register_btn_loading: 'అకౌంట్ తయారవుతోంది…',
    register_have_account: 'ఇప్పటికే అకౌంట్ ఉందా?', register_signin: 'సైన్ ఇన్',
    register_error: 'నమోదు విఫలమైంది. మళ్ళీ ప్రయత్నించండి.',
    forgot_title: 'పాస్‌వర్డ్ మర్చిపోయారు', forgot_email: 'ఇమెయిల్ చిరునామా',
    forgot_btn: 'రీసెట్ లింక్ పంపు', forgot_btn_loading: 'పంపుతోంది…',
    forgot_back: 'సైన్ ఇన్‌కు తిరిగి వెళ్ళు', forgot_success: 'రీసెట్ లింక్ పంపబడింది!',
    reset_title: 'పాస్‌వర్డ్ రీసెట్', reset_new_pw: 'కొత్త పాస్‌వర్డ్',
    reset_confirm_pw: 'పాస్‌వర్డ్ నిర్ధారించు',
    reset_btn: 'పాస్‌వర్డ్ రీసెట్', reset_btn_loading: 'రీసెట్ అవుతోంది…',
    reset_mismatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు.',
    profile_title: 'ప్రొఫైల్', profile_name: 'పూర్తి పేరు', profile_save_name: 'పేరు సేవ్',
    profile_saving: 'సేవ్ అవుతోంది…', profile_change_pw: 'పాస్‌వర్డ్ మార్చు',
    profile_current_pw: 'ప్రస్తుత పాస్‌వర్డ్', profile_new_pw: 'కొత్త పాస్‌వర్డ్',
    profile_save_pw: 'పాస్‌వర్డ్ అప్‌డేట్', profile_avatar: 'ప్రొఫైల్ చిత్రం',
    profile_change_avatar: 'ఫోటో మార్చు', profile_uploading: 'అప్‌లోడ్ అవుతోంది…',
    sessions_title: 'చదువు సెషన్లు', sessions_new: '+ కొత్త సెషన్',
    sessions_create_title: 'కొత్త చదువు సెషన్', sessions_form_title: 'సెషన్ శీర్షిక',
    sessions_form_subject: 'సబ్జెక్ట్', sessions_form_subject_ph: 'సబ్జెక్ట్ ఎంచుకో…',
    sessions_form_create: 'సెషన్ తయారుచేయి', sessions_form_creating: 'తయారవుతోంది…',
    sessions_form_cancel: 'రద్దు', sessions_active: 'చురుకుగా',
    sessions_completed: 'పూర్తయింది', sessions_mark_done: 'పూర్తిగా గుర్తించు',
    sessions_mark_active: 'చురుకుగా గుర్తించు', sessions_delete: 'తొలగించు',
    sessions_empty: 'ఇంకా సెషన్ లేదు', sessions_empty_sub: 'మొదటి సెషన్ తయారుచేయి.',
    notes_title: 'నోట్స్', notes_new: '+ కొత్త నోట్', notes_untitled: 'శీర్షిక లేని నోట్',
    notes_placeholder: 'రాయడం ప్రారంభించు…', notes_save: 'సేవ్',
    notes_saving: 'సేవ్ అవుతోంది…', notes_saved: 'సేవ్ అయింది ✓', notes_delete: 'తొలగించు',
    notes_empty: 'ఇంకా నోట్ లేదు', notes_empty_sub: 'ప్రారంభించడానికి నోట్ తయారుచేయి.',
    materials_title: 'చదువు పదార్థాలు', materials_upload: 'ఫైల్ అప్‌లోడ్',
    materials_drop: 'ఇక్కడ ఫైల్‌లు వేయి', materials_browse: 'లేదా క్లిక్ చేయి',
    materials_supported: 'PDF, చిత్రాలు, Word, PowerPoint, Excel — గరిష్టంగా 20 MB',
    materials_uploading: 'అప్‌లోడ్ అవుతోంది…', materials_empty: 'ఇంకా ఫైల్ లేదు',
    materials_empty_sub: 'మీ పదార్థాలు అప్‌లోడ్ చేయండి.', materials_delete: 'తొలగించు',
    checkin_title: 'రోజువారీ చెక్-ఇన్', checkin_date: 'తేదీ',
    checkin_study_hours: 'చదువు గంటలు', checkin_attendance: 'హాజరు %',
    checkin_completion: 'అసైన్‌మెంట్ పూర్తి %', checkin_quiz_score: 'క్విజ్ స్కోర్ (ఐచ్ఛికం)',
    checkin_exam_score: 'పరీక్ష స్కోర్ (ఐచ్ఛికం)', checkin_sleep: 'నిద్ర గంటలు',
    checkin_stress: 'ఒత్తిడి స్థాయి', checkin_notes: 'నోట్స్ (ఐచ్ఛికం)',
    checkin_notes_ph: 'మీ రోజు ఎలా ఉంది?', checkin_submit: 'చెక్-ఇన్ సమర్పించు',
    checkin_update: 'చెక్-ఇన్ అప్‌డేట్', checkin_submitting: 'సేవ్ అవుతోంది…',
    checkin_low: 'తక్కువ', checkin_moderate: 'మధ్యస్థం', checkin_high: 'ఎక్కువ',
    checkin_history: 'ఇటీవలి చెక్-ఇన్‌లు', checkin_empty: 'ఇంకా చెక్-ఇన్ లేదు.',
    predict_title: 'స్కోర్ అంచనా', predict_btn: 'నా స్కోర్ అంచనా వేయి',
    predict_predicting: 'అంచనా వేస్తోంది…', predict_score: 'అంచనా స్కోర్',
    predict_risk: 'ప్రమాద స్థాయి', predict_recommendations: 'సిఫారసులు',
    predict_contributions: 'లక్షణ ప్రభావం', predict_importance: 'లక్షణ ప్రాముఖ్యత',
    predict_fill_form: 'అంచనా కోసం మీ డేటా నమోదు చేయండి.',
    simulate_title: 'ఏమవుతుందో సిమ్యులేటర్', simulate_run: 'సిమ్యులేషన్ రన్',
    simulate_running: 'రన్ అవుతోంది…', simulate_reset: 'ప్రస్తుతానికి రీసెట్',
    simulate_current: 'ప్రస్తుత', simulate_hypothetical: 'కాల్పనిక',
    simulate_impact: 'స్కోర్ ప్రభావం', simulate_no_data: 'ఇటీవలి డేటా లేదు.',
    simulate_study_hours: 'చదువు గంటలు', simulate_attendance: 'హాజరు',
    simulate_completion: 'అసైన్‌మెంట్ పూర్తి', simulate_quiz: 'క్విజ్ స్కోర్',
    simulate_sleep: 'నిద్ర', simulate_stress: 'ఒత్తిడి',
    mentor_title: 'AI మెంటర్', mentor_send: 'పంపు',
    mentor_placeholder: 'మీ చదువు గురించి ఏమైనా అడగండి…',
    mentor_gen_plan: '30 రోజుల ప్రణాళిక రూపొందించు', mentor_plan_title: 'మీ 30 రోజుల ప్రణాళిక',
    mentor_save_plan: 'ప్రణాళిక సేవ్', mentor_plan_saved: 'ప్రణాళిక సేవ్ అయింది!',
    mentor_new_chat: 'కొత్త చాట్', mentor_sessions: 'సెషన్లు', mentor_generating: 'రూపొందుతోంది…',
    twin_title: 'డిజిటల్ ట్విన్', twin_health: 'ట్విన్ ఆరోగ్యం',
    twin_score: 'మొత్తం స్కోర్', twin_trend: 'ధోరణి',
    twin_strengths: 'బలాలు', twin_improve: 'మెరుగుపడాల్సిన రంగాలు',
    twin_future_30: '30 రోజుల అంచనా', twin_future_60: '60 రోజుల అంచనా',
    twin_future_90: '90 రోజుల అంచనా', twin_no_data: 'ఇంకా తగినంత డేటా లేదు.',
    twin_log_checkin: 'ట్విన్ పెరగడం చూడటానికి చెక్-ఇన్ చేయండి.',
    achievements_title: 'విజయాలు', achievements_earned: 'సంపాదించారు',
    achievements_locked: 'లాక్', achievements_empty: 'ఇంకా విజయాలు లేవు.',
    quiz_title: 'AI క్విజ్', quiz_configure: 'మీ క్విజ్ కాన్ఫిగర్ చేయి',
    quiz_powered: 'Groq AI తో నడిచే', quiz_subject: 'సబ్జెక్ట్',
    quiz_duration: 'వ్యవధి', quiz_difficulty: 'కష్టత',
    quiz_generate: 'క్విజ్ తయారుచేయి →', quiz_history: 'గత క్విజ్‌లు',
    quiz_easy: 'సులభం', quiz_medium: 'మధ్యస్థం', quiz_hard: 'కష్టం',
    quiz_easy_desc: 'ప్రాథమిక గుర్తుపెట్టుకోవడం మరియు సులభమైన భావనలు',
    quiz_medium_desc: 'అనువర్తిత అవగాహన మరియు మధ్యస్థ తార్కికత',
    quiz_hard_desc: 'లోతైన విశ్లేషణ మరియు బహుళ-దశ తార్కికత',
    quiz_generating: 'మీ క్విజ్ తయారవుతోంది…',
    quiz_no_subjects: 'ప్రొఫైల్‌లో సబ్జెక్ట్ లేదు.', quiz_add_subjects: 'సబ్జెక్ట్ జోడించు →',
    quiz_results_title: 'క్విజ్ ఫలితాలు', quiz_correct: 'సరైనది',
    quiz_wrong: 'తప్పు', quiz_skipped: 'వదిలేసారు', quiz_time: 'సమయం',
    quiz_review: 'సమాధాన సమీక్ష', quiz_take_another: 'మరొకటి తీసుకో →',
    quiz_take_another_btn: 'మరొక క్విజ్ తీసుకో',
    quiz_no_history: 'ఇంకా క్విజ్ తీసుకోలేదు.',
    quiz_finish: 'క్విజ్ ముగించు', quiz_next: 'తదుపరి ప్రశ్న',
  },

  mr: {
    nav_sessions: 'सत्रे', nav_notes: 'नोट्स', nav_materials: 'साहित्य',
    nav_progress: 'प्रगती', nav_checkin: 'चेक-इन', nav_achievements: 'उपलब्धी',
    nav_quiz: 'प्रश्नमंजुषा', nav_simulate: 'अनुकरण', nav_mentor: 'मार्गदर्शक', nav_twin: 'ट्विन',
    sign_out: 'साइन आउट', loading: 'लोड होत आहे…', live: 'लाइव्ह',
    save: 'जतन करा', cancel: 'रद्द करा', delete: 'हटवा', close: 'बंद करा',
    back_dashboard: '← डॅशबोर्ड',
    greeting_midnight: 'मध्यरात्री काम करत आहात', greeting_morning: 'शुभ सकाळ',
    greeting_afternoon: 'नमस्कार', greeting_evening: 'शुभ संध्याकाळ',
    hero_sub: 'आजचा दिवस सार्थकी लावा?',
    stat_sessions: 'सत्रे', stat_hours: 'अभ्यास तास', stat_streak: 'दिवसांची मालिका',
    stat_notes: 'नोट्स', stat_badges: 'मिळवलेले बॅज',
    chart_title: 'अभ्यास तास — मागील ७ दिवस', chart_log_today: '+ आज नोंदवा',
    chart_this_week: 'या आठवड्यात', chart_daily_avg: 'दैनिक सरासरी',
    no_data_title: 'अद्याप डेटा नाही', no_data_sub: 'चार्ट पाहण्यासाठी पहिले चेक-इन करा.',
    no_data_btn: 'आज नोंदवा →',
    quick_actions: 'त्वरित क्रिया',
    qa_sessions: 'सत्रे', qa_materials: 'साहित्य', qa_progress: 'प्रगती',
    qa_quiz: 'प्रश्नमंजुषा', qa_predict: 'अंदाज', qa_achievements: 'उपलब्धी',
    qa_simulate: 'अनुकरण', qa_mentor: 'मार्गदर्शक', qa_twin: 'ट्विन',
    qa_checkin: 'चेक-इन', qa_language: 'भाषा',
    qa_desc_study: 'अभ्यास', qa_desc_upload: 'अपलोड', qa_desc_analytics: 'विश्लेषण',
    qa_desc_quiz: 'AI प्रश्नमंजुषा', qa_desc_ml: 'ML गुण', qa_desc_badges: 'बॅज',
    qa_desc_whatif: 'काय-जर', qa_desc_advice: 'AI सल्ला', qa_desc_twin: 'डिजिटल ट्विन',
    qa_desc_log: 'नोंदवा', qa_desc_language: 'बदला',
    my_study_plan: 'माझी अभ्यास योजना', generate_new: 'नवीन तयार करा →',
    view_full_plan: 'संपूर्ण योजना पाहा',
    no_plan_title: 'अद्याप कोणतीही योजना नाही',
    no_plan_sub: 'AI मार्गदर्शकात ३०-दिवसीय योजना तयार करा.',
    go_to_mentor: 'मार्गदर्शकाकडे जा →', plan_saved: 'जतन केले',
    modal_plan_title: '३०-दिवसीय अभ्यास योजना', modal_regenerate: 'मार्गदर्शकात पुन्हा तयार करा →',
    language_title: 'भाषा निवडा', language_select: 'आपली पसंतीची भाषा निवडा',
    login_tagline: 'तुमचा AI-चालित शैक्षणिक ट्विन', login_title: 'पुन्हा स्वागत आहे',
    login_email: 'ईमेल', login_password: 'पासवर्ड', login_forgot: 'पासवर्ड विसरलात?',
    login_btn: 'साइन इन →', login_btn_loading: 'साइन इन होत आहे…',
    login_no_account: 'खाते नाही?', login_create: 'तयार करा',
    login_error: 'अवैध ईमेल किंवा पासवर्ड.',
    register_title: 'खाते तयार करा', register_fullname: 'पूर्ण नाव',
    register_email: 'ईमेल', register_password: 'पासवर्ड',
    register_btn: 'सुरुवात करा →', register_btn_loading: 'खाते तयार होत आहे…',
    register_have_account: 'आधीच खाते आहे?', register_signin: 'साइन इन',
    register_error: 'नोंदणी अयशस्वी. पुन्हा प्रयत्न करा.',
    forgot_title: 'पासवर्ड विसरलात', forgot_email: 'ईमेल पत्ता',
    forgot_btn: 'रीसेट लिंक पाठवा', forgot_btn_loading: 'पाठवत आहे…',
    forgot_back: 'साइन इनवर परत', forgot_success: 'रीसेट लिंक पाठवला! इनबॉक्स तपासा.',
    reset_title: 'पासवर्ड रीसेट', reset_new_pw: 'नवीन पासवर्ड',
    reset_confirm_pw: 'पासवर्ड पुष्टी करा',
    reset_btn: 'पासवर्ड रीसेट', reset_btn_loading: 'रीसेट होत आहे…',
    reset_mismatch: 'पासवर्ड जुळत नाहीत.',
    profile_title: 'प्रोफाइल', profile_name: 'पूर्ण नाव', profile_save_name: 'नाव जतन करा',
    profile_saving: 'जतन होत आहे…', profile_change_pw: 'पासवर्ड बदला',
    profile_current_pw: 'सध्याचा पासवर्ड', profile_new_pw: 'नवीन पासवर्ड',
    profile_save_pw: 'पासवर्ड अपडेट करा', profile_avatar: 'प्रोफाइल चित्र',
    profile_change_avatar: 'फोटो बदला', profile_uploading: 'अपलोड होत आहे…',
    sessions_title: 'अभ्यास सत्रे', sessions_new: '+ नवीन सत्र',
    sessions_create_title: 'नवीन अभ्यास सत्र', sessions_form_title: 'सत्राचे शीर्षक',
    sessions_form_subject: 'विषय', sessions_form_subject_ph: 'विषय निवडा…',
    sessions_form_create: 'सत्र तयार करा', sessions_form_creating: 'तयार होत आहे…',
    sessions_form_cancel: 'रद्द करा', sessions_active: 'सक्रिय',
    sessions_completed: 'पूर्ण', sessions_mark_done: 'पूर्ण म्हणून चिन्हांकित करा',
    sessions_mark_active: 'सक्रिय म्हणून चिन्हांकित करा', sessions_delete: 'हटवा',
    sessions_empty: 'अद्याप सत्र नाही', sessions_empty_sub: 'वर पहिले सत्र तयार करा.',
    notes_title: 'नोट्स', notes_new: '+ नवीन नोट', notes_untitled: 'शीर्षकहीन नोट',
    notes_placeholder: 'लिहायला सुरुवात करा…', notes_save: 'जतन करा',
    notes_saving: 'जतन होत आहे…', notes_saved: 'जतन केले ✓', notes_delete: 'हटवा',
    notes_empty: 'अद्याप नोट नाही', notes_empty_sub: 'सुरुवात करण्यासाठी नोट तयार करा.',
    materials_title: 'अभ्यास साहित्य', materials_upload: 'फाईल अपलोड करा',
    materials_drop: 'येथे फाइल्स टाका', materials_browse: 'किंवा ब्राउझ करण्यासाठी क्लिक करा',
    materials_supported: 'PDF, चित्रे, Word, PowerPoint, Excel — कमाल 20 MB',
    materials_uploading: 'अपलोड होत आहे…', materials_empty: 'अद्याप फाईल नाही',
    materials_empty_sub: 'आपले साहित्य अपलोड करा.', materials_delete: 'हटवा',
    checkin_title: 'दैनिक चेक-इन', checkin_date: 'तारीख',
    checkin_study_hours: 'अभ्यास तास', checkin_attendance: 'उपस्थिती %',
    checkin_completion: 'असाइनमेंट पूर्णता %', checkin_quiz_score: 'प्रश्नमंजुषा गुण (पर्यायी)',
    checkin_exam_score: 'परीक्षा गुण (पर्यायी)', checkin_sleep: 'झोपेचे तास',
    checkin_stress: 'तणावाची पातळी', checkin_notes: 'नोट्स (पर्यायी)',
    checkin_notes_ph: 'तुमचा दिवस कसा होता?', checkin_submit: 'चेक-इन सादर करा',
    checkin_update: 'चेक-इन अपडेट करा', checkin_submitting: 'जतन होत आहे…',
    checkin_low: 'कमी', checkin_moderate: 'मध्यम', checkin_high: 'जास्त',
    checkin_history: 'अलीकडील चेक-इन', checkin_empty: 'अद्याप चेक-इन नाही.',
    predict_title: 'गुण अंदाजक', predict_btn: 'माझा गुण अंदाज करा',
    predict_predicting: 'अंदाज होत आहे…', predict_score: 'अंदाजित गुण',
    predict_risk: 'धोक्याची पातळी', predict_recommendations: 'शिफारसी',
    predict_contributions: 'वैशिष्ट्य प्रभाव', predict_importance: 'वैशिष्ट्य महत्त्व',
    predict_fill_form: 'अंदाजासाठी आपला डेटा भरा.',
    simulate_title: 'काय-जर सिम्युलेटर', simulate_run: 'सिम्युलेशन चालवा',
    simulate_running: 'चालू आहे…', simulate_reset: 'सध्याच्यावर रीसेट',
    simulate_current: 'सध्याचे', simulate_hypothetical: 'काल्पनिक',
    simulate_impact: 'गुण प्रभाव', simulate_no_data: 'अलीकडील डेटा नाही.',
    simulate_study_hours: 'अभ्यास तास', simulate_attendance: 'उपस्थिती',
    simulate_completion: 'असाइनमेंट पूर्णता', simulate_quiz: 'प्रश्नमंजुषा गुण',
    simulate_sleep: 'झोप', simulate_stress: 'तणाव',
    mentor_title: 'AI मार्गदर्शक', mentor_send: 'पाठवा',
    mentor_placeholder: 'अभ्यासाबद्दल काहीही विचारा…',
    mentor_gen_plan: '३०-दिवसीय योजना तयार करा', mentor_plan_title: 'तुमची ३०-दिवसीय योजना',
    mentor_save_plan: 'योजना जतन करा', mentor_plan_saved: 'योजना जतन केली!',
    mentor_new_chat: 'नवीन चॅट', mentor_sessions: 'सत्रे', mentor_generating: 'तयार होत आहे…',
    twin_title: 'डिजिटल ट्विन', twin_health: 'ट्विन आरोग्य',
    twin_score: 'एकूण गुण', twin_trend: 'कल',
    twin_strengths: 'बलस्थाने', twin_improve: 'सुधारणेचे क्षेत्र',
    twin_future_30: '३०-दिवसांचा अंदाज', twin_future_60: '६०-दिवसांचा अंदाज',
    twin_future_90: '९०-दिवसांचा अंदाज', twin_no_data: 'अद्याप पुरेसा डेटा नाही.',
    twin_log_checkin: 'ट्विन विकसित होताना पाहण्यासाठी चेक-इन करा.',
    achievements_title: 'उपलब्धी', achievements_earned: 'मिळवले',
    achievements_locked: 'बंद', achievements_empty: 'अद्याप उपलब्धी नाही.',
    quiz_title: 'AI प्रश्नमंजुषा', quiz_configure: 'तुमची प्रश्नमंजुषा कॉन्फिगर करा',
    quiz_powered: 'Groq AI द्वारे संचालित', quiz_subject: 'विषय',
    quiz_duration: 'कालावधी', quiz_difficulty: 'अडचण',
    quiz_generate: 'प्रश्नमंजुषा तयार करा →', quiz_history: 'मागील प्रश्नमंजुषा',
    quiz_easy: 'सोपे', quiz_medium: 'मध्यम', quiz_hard: 'कठीण',
    quiz_easy_desc: 'मूलभूत स्मरण आणि सोप्या संकल्पना',
    quiz_medium_desc: 'उपयोजित समज आणि मध्यम तर्क',
    quiz_hard_desc: 'सखोल विश्लेषण आणि बहु-टप्पा तर्क',
    quiz_generating: 'तुमची प्रश्नमंजुषा तयार होत आहे…',
    quiz_no_subjects: 'प्रोफाइलमध्ये विषय नाही.', quiz_add_subjects: 'विषय जोडा →',
    quiz_results_title: 'प्रश्नमंजुषा निकाल', quiz_correct: 'बरोबर',
    quiz_wrong: 'चुकीचे', quiz_skipped: 'वगळले', quiz_time: 'वेळ',
    quiz_review: 'उत्तर आढावा', quiz_take_another: 'आणखी एक घ्या →',
    quiz_take_another_btn: 'आणखी एक प्रश्नमंजुषा घ्या',
    quiz_no_history: 'अद्याप प्रश्नमंजुषा घेतली नाही.',
    quiz_finish: 'प्रश्नमंजुषा समाप्त', quiz_next: 'पुढील प्रश्न',
  },
};

interface LanguageContextValue {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    const saved = localStorage.getItem('twinmind_lang');
    if (saved && saved in T) return saved as LangCode;
    return 'en';
  });

  function setLang(l: LangCode) {
    localStorage.setItem('twinmind_lang', l);
    setLangState(l);
  }

  function t(key: string): string {
    return T[lang][key] ?? T['en'][key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
